### ISSUE TITLE
May I inquire about the size of the model?

### ISSUE THREAD

**Issue by Tangjj1996** [LucienShui/huggingface-vscode-endpoint-server#3]
Thank you very much for your contribution. It's seems like an impressive work!

I'm a beginner in learning about large models. Conld you please let me know how long the installation of this model ususlly takes and the required CPU and GPU resources? Additionally, if you have any relevant learning tutorials or resources, that would be greatly appreciated.

![image](https://github.com/LucienShui/huggingface-vscode-endpoint-server/assets/44096988/d6eae53d-703b-468e-a052-16346c723bf5)

Thanks!

**Comment by LucienShui** [comment]
The CPU isn't all that critical, two NVIDIA RTX 3090s with 24G CUDA memory should be able to handle loading and inferencing with `fp16` precision.

The time it takes to download the model is largely contingent upon your network speed, while the time to load the model from local storage is determined by your disk speed.

Given that the model size is approximately 60GB, you should be able to estimate the time required on your own.

Tutorial reference: https://huggingface.co/docs/transformers/autoclass_tutorial
