### ISSUE TITLE
any chance to config the model local foler?

### ISSUE THREAD

**Issue by luckyfish0826** [LucienShui/huggingface-vscode-endpoint-server#7]
so we could save the model download time and use our own custom model bin file. Thanks

**Comment by luckyfish0826** [comment]
> You can download the model seperatly to any destination you like and then point the endpoint-server to the directory, i.e. `python main.py --pretrained="../my_model"`

Thanks, yes seems it's not working, I'll try more ways and let you know the result.

**Comment by LucienShui** [comment]
It seems you've done what you want, if there's still any problem, you can reopen it.

**Comment by iamjameswalters** [comment]
> You can download the model seperatly to any destination you like and then point the endpoint-server to the directory, i.e. `python main.py --pretrained="../my_model"`

Could you explain this? I have no idea what "download the model" means. Where are we getting it?
